name: indoorly
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_unity_widget: ^0.1.6+5
  cloud_firestore: ^0.12.11
  google_sign_in: ^4.0.7
  firebase_auth: ^0.15.1
  permission_handler: ^4.0.0
  shared_preferences: ^0.5.4+8
  google_fonts: ^0.1.1
  flutter_spinkit: ^4.1.0
  font_awesome_flutter: ^8.5.0
  provider: ^3.2.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
